package com.datavirtue.nevitiumpro.data.factories;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.BeanNameAware;

import com.datavirtue.nevitiumpro.data.model.dao.*;

/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class HibernateNevitiumProDaoFactory implements ApplicationContextAware, BeanNameAware {
	/** Placeholder for an instance. */
	private static HibernateNevitiumProDaoFactory instance;
	/** Internal state. */
	private static ApplicationContext context = null;
	/** Bean Name. */
	private static String beanName;

	/** Return an instance of this class.
	 * @return an instance of this class
	 */
	public static synchronized HibernateNevitiumProDaoFactory getInstance() {
		if (instance == null) {
			instance = (HibernateNevitiumProDaoFactory) context.getBean(beanName);
		}
		return instance;
	}

	/**
	 * Sets a Spring Application Context object.
  	 * @param ctxt ApplicationContext to set
	 * @throws BeansException on spring error
	 */
	@Autowired
	public void setApplicationContext(ApplicationContext ctxt)
			throws BeansException 
	{
		context = ctxt;
	}

	/**
	* 
	* {@inheritDoc}
	* 
	* @see org.springframework.beans.factory.BeanNameAware#setBeanName(java.lang.String)
	*/
	public void setBeanName(String name) {
		beanName = name;
	}

	/**
	 * Return the requested bean from the context, throwing a RuntimeException on error.
	 *
	 * @param beanName to return
	 * @return the bean requested.
	 */
	public static Object getBean(String beanName) {
		Object result = context.getBean(beanName);
		if (result == null) { 
			throw new IllegalStateException(String.format("Could not find bean '%s'. Did you set the right component scanning?", beanName));
		} 
		
		return result;
	}

	
	/**
	 * Returns a ConnectionsDao instance.
	 * 
	 * @return a ConnectionsDao instance
	 */
	public static ConnectionsDao getConnectionsDao() {
		return (ConnectionsDao) getBean("connectionsDaoImpl"); 
	}
	/**
	 * Returns a ConnectionsDocumentsDao instance.
	 * 
	 * @return a ConnectionsDocumentsDao instance
	 */
	public static ConnectionsDocumentsDao getConnectionsDocumentsDao() {
		return (ConnectionsDocumentsDao) getBean("connectionsDocumentsDaoImpl"); 
	}
	/**
	 * Returns a ConnectionsShippingDao instance.
	 * 
	 * @return a ConnectionsShippingDao instance
	 */
	public static ConnectionsShippingDao getConnectionsShippingDao() {
		return (ConnectionsShippingDao) getBean("connectionsShippingDaoImpl"); 
	}
	/**
	 * Returns a CreditAccountLedgerDao instance.
	 * 
	 * @return a CreditAccountLedgerDao instance
	 */
	public static CreditAccountLedgerDao getCreditAccountLedgerDao() {
		return (CreditAccountLedgerDao) getBean("creditAccountLedgerDaoImpl"); 
	}
	/**
	 * Returns a CreditAccountsDao instance.
	 * 
	 * @return a CreditAccountsDao instance
	 */
	public static CreditAccountsDao getCreditAccountsDao() {
		return (CreditAccountsDao) getBean("creditAccountsDaoImpl"); 
	}
	/**
	 * Returns a DebitAccountLedgerDao instance.
	 * 
	 * @return a DebitAccountLedgerDao instance
	 */
	public static DebitAccountLedgerDao getDebitAccountLedgerDao() {
		return (DebitAccountLedgerDao) getBean("debitAccountLedgerDaoImpl"); 
	}
	/**
	 * Returns a DebitAccountsDao instance.
	 * 
	 * @return a DebitAccountsDao instance
	 */
	public static DebitAccountsDao getDebitAccountsDao() {
		return (DebitAccountsDao) getBean("debitAccountsDaoImpl"); 
	}
	/**
	 * Returns a InventoryDao instance.
	 * 
	 * @return a InventoryDao instance
	 */
	public static InventoryDao getInventoryDao() {
		return (InventoryDao) getBean("inventoryDaoImpl"); 
	}
	/**
	 * Returns a InventoryHasConnectionsDao instance.
	 * 
	 * @return a InventoryHasConnectionsDao instance
	 */
	public static InventoryHasConnectionsDao getInventoryHasConnectionsDao() {
		return (InventoryHasConnectionsDao) getBean("inventoryHasConnectionsDaoImpl"); 
	}
	/**
	 * Returns a InventoryImagesDao instance.
	 * 
	 * @return a InventoryImagesDao instance
	 */
	public static InventoryImagesDao getInventoryImagesDao() {
		return (InventoryImagesDao) getBean("inventoryImagesDaoImpl"); 
	}
	/**
	 * Returns a InvoiceItemsDao instance.
	 * 
	 * @return a InvoiceItemsDao instance
	 */
	public static InvoiceItemsDao getInvoiceItemsDao() {
		return (InvoiceItemsDao) getBean("invoiceItemsDaoImpl"); 
	}
	/**
	 * Returns a InvoicePaymentsDao instance.
	 * 
	 * @return a InvoicePaymentsDao instance
	 */
	public static InvoicePaymentsDao getInvoicePaymentsDao() {
		return (InvoicePaymentsDao) getBean("invoicePaymentsDaoImpl"); 
	}
	/**
	 * Returns a InvoiceReturnsDao instance.
	 * 
	 * @return a InvoiceReturnsDao instance
	 */
	public static InvoiceReturnsDao getInvoiceReturnsDao() {
		return (InvoiceReturnsDao) getBean("invoiceReturnsDaoImpl"); 
	}
	/**
	 * Returns a InvoicesDao instance.
	 * 
	 * @return a InvoicesDao instance
	 */
	public static InvoicesDao getInvoicesDao() {
		return (InvoicesDao) getBean("invoicesDaoImpl"); 
	}
	/**
	 * Returns a ProjectsDao instance.
	 * 
	 * @return a ProjectsDao instance
	 */
	public static ProjectsDao getProjectsDao() {
		return (ProjectsDao) getBean("projectsDaoImpl"); 
	}
	/**
	 * Returns a ProjectsHasConnectionsDao instance.
	 * 
	 * @return a ProjectsHasConnectionsDao instance
	 */
	public static ProjectsHasConnectionsDao getProjectsHasConnectionsDao() {
		return (ProjectsHasConnectionsDao) getBean("projectsHasConnectionsDaoImpl"); 
	}
	/**
	 * Returns a ProjectsHasInvoicesDao instance.
	 * 
	 * @return a ProjectsHasInvoicesDao instance
	 */
	public static ProjectsHasInvoicesDao getProjectsHasInvoicesDao() {
		return (ProjectsHasInvoicesDao) getBean("projectsHasInvoicesDaoImpl"); 
	}
	/**
	 * Returns a ProjectsHasQuotesDao instance.
	 * 
	 * @return a ProjectsHasQuotesDao instance
	 */
	public static ProjectsHasQuotesDao getProjectsHasQuotesDao() {
		return (ProjectsHasQuotesDao) getBean("projectsHasQuotesDaoImpl"); 
	}
	/**
	 * Returns a QuoteItemsDao instance.
	 * 
	 * @return a QuoteItemsDao instance
	 */
	public static QuoteItemsDao getQuoteItemsDao() {
		return (QuoteItemsDao) getBean("quoteItemsDaoImpl"); 
	}
	/**
	 * Returns a QuotesDao instance.
	 * 
	 * @return a QuotesDao instance
	 */
	public static QuotesDao getQuotesDao() {
		return (QuotesDao) getBean("quotesDaoImpl"); 
	}
	/**
	 * Returns a UserAccountDao instance.
	 * 
	 * @return a UserAccountDao instance
	 */
	public static UserAccountDao getUserAccountDao() {
		return (UserAccountDao) getBean("UserAccountDaoImpl"); 
	}

}
