package com.datavirtue.nevitiumpro.data.services.datalayer;

import com.datavirtue.nevitiumpro.data.model.obj.Connections;
import com.datavirtue.nevitiumpro.data.model.obj.ConnectionsDocuments;
import com.datavirtue.nevitiumpro.data.model.obj.ConnectionsShipping;
import com.datavirtue.nevitiumpro.data.model.obj.CreditAccountLedger;
import com.datavirtue.nevitiumpro.data.model.obj.CreditAccounts;
import com.datavirtue.nevitiumpro.data.model.obj.DebitAccountLedger;
import com.datavirtue.nevitiumpro.data.model.obj.DebitAccounts;
import com.datavirtue.nevitiumpro.data.model.obj.Inventory;
import com.datavirtue.nevitiumpro.data.model.obj.InventoryHasConnections;
import com.datavirtue.nevitiumpro.data.model.obj.InventoryHasConnectionsPK;
import com.datavirtue.nevitiumpro.data.model.obj.InventoryImages;
import com.datavirtue.nevitiumpro.data.model.obj.InvoiceItems;
import com.datavirtue.nevitiumpro.data.model.obj.InvoicePayments;
import com.datavirtue.nevitiumpro.data.model.obj.InvoiceReturns;
import com.datavirtue.nevitiumpro.data.model.obj.Invoices;
import com.datavirtue.nevitiumpro.data.model.obj.Projects;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasConnections;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasConnectionsPK;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasInvoices;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasInvoicesPK;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasQuotes;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasQuotesPK;
import com.datavirtue.nevitiumpro.data.model.obj.QuoteItems;
import com.datavirtue.nevitiumpro.data.model.obj.Quotes;
import com.datavirtue.nevitiumpro.data.model.obj.UserAccount;
import java.io.Serializable;
import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.SQLQuery;
import org.hibernate.ReplicationMode;
import org.hibernate.Session;
import java.util.Collection;
import com.felees.hbnpojogen.persistence.IPojoGenEntity;
/** 
 * Data layer.
 * @author autogenerated
 */
public interface DataLayerNevitiumPro {

    /**
     * Deletes the given object from disk.
     * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to delete
     */
    <T> void delete(T persistentObject);
    /**
     * Refresh the object $class.className from disk.
     * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to reload
     */
    <T> void refresh(T persistentObject);

    /**
     * Saves the given object to disk.
     * @param persistentObject Object to save
	 * @param <T> A DataLayerObject-derived type
     * @return Identifier of saved object 
     */
    <T> Serializable save(T persistentObject);
    /**
     * Saves or updates the given $class.className object to disk.
	 * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to save 
     */
    <T> void saveOrUpdate(T persistentObject);
    /**
     * Updates the given object to disk.
	 * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to update 
     */
    <T> void update(T persistentObject);


    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Connections obj) directly
     * @param id Identifier to delete
     */
    void deleteConnections(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Connections object
     */
    Connections loadConnections(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Connections getConnections(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ConnectionsDocuments obj) directly
     * @param id Identifier to delete
     */
    void deleteConnectionsDocuments(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ConnectionsDocuments object
     */
    ConnectionsDocuments loadConnectionsDocuments(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     ConnectionsDocuments getConnectionsDocuments(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ConnectionsShipping obj) directly
     * @param id Identifier to delete
     */
    void deleteConnectionsShipping(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ConnectionsShipping object
     */
    ConnectionsShipping loadConnectionsShipping(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     ConnectionsShipping getConnectionsShipping(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (CreditAccounts obj) directly
     * @param id Identifier to delete
     */
    void deleteCreditAccounts(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a CreditAccounts object
     */
    CreditAccounts loadCreditAccounts(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     CreditAccounts getCreditAccounts(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (CreditAccountLedger obj) directly
     * @param id Identifier to delete
     */
    void deleteCreditAccountLedger(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a CreditAccountLedger object
     */
    CreditAccountLedger loadCreditAccountLedger(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     CreditAccountLedger getCreditAccountLedger(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (DebitAccounts obj) directly
     * @param id Identifier to delete
     */
    void deleteDebitAccounts(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a DebitAccounts object
     */
    DebitAccounts loadDebitAccounts(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     DebitAccounts getDebitAccounts(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (DebitAccountLedger obj) directly
     * @param id Identifier to delete
     */
    void deleteDebitAccountLedger(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a DebitAccountLedger object
     */
    DebitAccountLedger loadDebitAccountLedger(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     DebitAccountLedger getDebitAccountLedger(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Inventory obj) directly
     * @param id Identifier to delete
     */
    void deleteInventory(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Inventory object
     */
    Inventory loadInventory(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Inventory getInventory(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (InventoryHasConnections obj) directly
     * @param id Identifier to delete
     */
    void deleteInventoryHasConnections(final InventoryHasConnectionsPK id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a InventoryHasConnections object
     */
    InventoryHasConnections loadInventoryHasConnections(final InventoryHasConnectionsPK id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     InventoryHasConnections getInventoryHasConnections(final InventoryHasConnectionsPK id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (InventoryImages obj) directly
     * @param id Identifier to delete
     */
    void deleteInventoryImages(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a InventoryImages object
     */
    InventoryImages loadInventoryImages(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     InventoryImages getInventoryImages(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Invoices obj) directly
     * @param id Identifier to delete
     */
    void deleteInvoices(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Invoices object
     */
    Invoices loadInvoices(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Invoices getInvoices(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (InvoiceItems obj) directly
     * @param id Identifier to delete
     */
    void deleteInvoiceItems(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a InvoiceItems object
     */
    InvoiceItems loadInvoiceItems(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     InvoiceItems getInvoiceItems(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (InvoicePayments obj) directly
     * @param id Identifier to delete
     */
    void deleteInvoicePayments(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a InvoicePayments object
     */
    InvoicePayments loadInvoicePayments(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     InvoicePayments getInvoicePayments(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (InvoiceReturns obj) directly
     * @param id Identifier to delete
     */
    void deleteInvoiceReturns(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a InvoiceReturns object
     */
    InvoiceReturns loadInvoiceReturns(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     InvoiceReturns getInvoiceReturns(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Projects obj) directly
     * @param id Identifier to delete
     */
    void deleteProjects(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Projects object
     */
    Projects loadProjects(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Projects getProjects(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ProjectsHasConnections obj) directly
     * @param id Identifier to delete
     */
    void deleteProjectsHasConnections(final ProjectsHasConnectionsPK id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ProjectsHasConnections object
     */
    ProjectsHasConnections loadProjectsHasConnections(final ProjectsHasConnectionsPK id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     ProjectsHasConnections getProjectsHasConnections(final ProjectsHasConnectionsPK id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ProjectsHasInvoices obj) directly
     * @param id Identifier to delete
     */
    void deleteProjectsHasInvoices(final ProjectsHasInvoicesPK id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ProjectsHasInvoices object
     */
    ProjectsHasInvoices loadProjectsHasInvoices(final ProjectsHasInvoicesPK id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     ProjectsHasInvoices getProjectsHasInvoices(final ProjectsHasInvoicesPK id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (ProjectsHasQuotes obj) directly
     * @param id Identifier to delete
     */
    void deleteProjectsHasQuotes(final ProjectsHasQuotesPK id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a ProjectsHasQuotes object
     */
    ProjectsHasQuotes loadProjectsHasQuotes(final ProjectsHasQuotesPK id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     ProjectsHasQuotes getProjectsHasQuotes(final ProjectsHasQuotesPK id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Quotes obj) directly
     * @param id Identifier to delete
     */
    void deleteQuotes(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Quotes object
     */
    Quotes loadQuotes(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Quotes getQuotes(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (QuoteItems obj) directly
     * @param id Identifier to delete
     */
    void deleteQuoteItems(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a QuoteItems object
     */
    QuoteItems loadQuoteItems(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     QuoteItems getQuoteItems(final Integer id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (UserAccount obj) directly
     * @param id Identifier to delete
     */
    void deleteUserAccount(final Integer id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a UserAccount object
     */
    UserAccount loadUserAccount(final Integer id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     UserAccount getUserAccount(final Integer id);  
    /** Returns a query handle.
     * @param query Query to use
     * @return A query instance
     */
     Query createQuery(final String query);
    /** Returns a criteria handle.
     * @param criteria Criteria to use
     * @return A criteria instance
     */
     Criteria createCriteria(final String criteria);
    /** Returns a Query handle based on your package-level named query.
     * @param query Query to use
     * @return A query instance
     */
     Query getNamedQuery(final String query);
    /** Create a new Criteria instance, for the given entity class, or a superclass of an entity class.
	* @param persistentObject a class, which is persistent, or has persistent subclasses 
	* @return Criteria instance
	*/
	@SuppressWarnings("unchecked")
	Criteria createCriteria(Class persistentObject);
    /** Flushes the currently open session.
	*/
	void flushSession();
    /** Clears the currently open session.
	*/
	void clearSession();
    /** Flushes and clears the currently open session.
	*/
	void flushAndClearSession();
	/** Call currentSession.replicate.
	 * @param obj to replicate
	 * @param replicationMode mode
	 */ 
	void replicate(Object obj, ReplicationMode replicationMode);
	/** Hibernate Merge. 
	 * @param obj to merge
	 * @return obj merged.
	 */
	Object merge(Object obj);
	/** Returns the current session.
	 * @return the currently active session
	 */
	Session getCurrentSession();
	/** Returns a query handle.
     * @param query Query to use
     * @return A query instance
     */
     SQLQuery createSQLQuery(final String query);
    /** Remove this instance from the session cache. 
	 * Changes to the instance will not be synchronized with the database
	 * @param obj object to evict
	 */
	void evict(Object obj);
    /**
     * Return the persistent instance of the given entity class with the given 
     * identifier, or null if there is no such persistent instance. 
     * (If the instance, or a proxy for the instance, is already 
     * associated with the session, return that instance or proxy)
     *
     * @param clazz a persistent class
     * @param id a valid identifier of an existing persistent instance of the class
     * @return a persistent instance or null
     * @throws HibernateException
     */
	Object get(Class<?> clazz, Serializable id) throws HibernateException;	


    /**
     * Return the persistent instance of the given entity class with the given identifier, assuming that the instance exists.
     *You should not use this method to determine if an instance exists (use get() instead). Use this only to retrieve an instance that you assume exists, where non-existence would be an actual error.
     *
     * @param clazz a persistent class
     * @param id a valid identifier of an existing persistent instance of the class
     * @return the persistent instance or proxy
     * @throws HibernateException
     */
	Object load(Class<?> clazz, Serializable id) throws HibernateException;
	/**
	 * Reattaches the given entity to the current session using LockMode.NONE
	 *
	 * @param entity to reattach
	 */
	void reattachEntityWithNoLock(IPojoGenEntity entity);
	/**
	 * Reattaches the given entities to the current session.
	 *
	 * @param entities to attach
	 */
	void reattachEntitiesWithNoLock(Collection<? extends IPojoGenEntity> entities);}

