package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.ConnectionsShipping;
 
/**
 * DAO interface for table: ConnectionsShipping.
 * @author autogenerated
 */
public interface ConnectionsShippingDao extends GenericDAO<ConnectionsShipping,  Integer>  {
	// constructor only
}

