package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.Connections;
 
/**
 * DAO interface for table: Connections.
 * @author autogenerated
 */
public interface ConnectionsDao extends GenericDAO<Connections,  Integer>  {
	// constructor only
}

