package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.ConnectionsDocuments;
 
/**
 * DAO interface for table: ConnectionsDocuments.
 * @author autogenerated
 */
public interface ConnectionsDocumentsDao extends GenericDAO<ConnectionsDocuments,  Integer>  {
	// constructor only
}

