package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.CreditAccounts;
 
/**
 * DAO interface for table: CreditAccounts.
 * @author autogenerated
 */
public interface CreditAccountsDao extends GenericDAO<CreditAccounts,  Integer>  {
	// constructor only
}

