package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.CreditAccountLedger;
 
/**
 * DAO interface for table: CreditAccountLedger.
 * @author autogenerated
 */
public interface CreditAccountLedgerDao extends GenericDAO<CreditAccountLedger,  Integer>  {
	// constructor only
}

