package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.DebitAccountLedger;
 
/**
 * DAO interface for table: DebitAccountLedger.
 * @author autogenerated
 */
public interface DebitAccountLedgerDao extends GenericDAO<DebitAccountLedger,  Integer>  {
	// constructor only
}

