package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.DebitAccounts;
 
/**
 * DAO interface for table: DebitAccounts.
 * @author autogenerated
 */
public interface DebitAccountsDao extends GenericDAO<DebitAccounts,  Integer>  {
	// constructor only
}

