package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.InventoryHasConnections;
import com.datavirtue.nevitiumpro.data.model.obj.InventoryHasConnectionsPK;
/**
 * DAO interface for table: InventoryHasConnections.
 * @author autogenerated
 */
public interface InventoryHasConnectionsDao extends GenericDAO<InventoryHasConnections,  InventoryHasConnectionsPK>  {
	// constructor only
}

