package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.Inventory;
 
/**
 * DAO interface for table: Inventory.
 * @author autogenerated
 */
public interface InventoryDao extends GenericDAO<Inventory,  Integer>  {
	// constructor only
}

