package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.InventoryImages;
 
/**
 * DAO interface for table: InventoryImages.
 * @author autogenerated
 */
public interface InventoryImagesDao extends GenericDAO<InventoryImages,  Integer>  {
	// constructor only
}

