package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.InventoryHasConnectionsPK;
import java.io.Serializable;
/**
 * DAO interface for table: InventoryHasConnectionsPK.
 * @author autogenerated
 */
public interface InventoryHasConnectionsPKDao extends GenericDAO<InventoryHasConnectionsPK,  Serializable>  {
	// constructor only
}

