package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.InvoiceItems;
 
/**
 * DAO interface for table: InvoiceItems.
 * @author autogenerated
 */
public interface InvoiceItemsDao extends GenericDAO<InvoiceItems,  Integer>  {
	// constructor only
}

