package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.Invoices;
 
/**
 * DAO interface for table: Invoices.
 * @author autogenerated
 */
public interface InvoicesDao extends GenericDAO<Invoices,  Integer>  {
	// constructor only
}

