package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.InvoiceReturns;
 
/**
 * DAO interface for table: InvoiceReturns.
 * @author autogenerated
 */
public interface InvoiceReturnsDao extends GenericDAO<InvoiceReturns,  Integer>  {
	// constructor only
}

