package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.InvoicePayments;
 
/**
 * DAO interface for table: InvoicePayments.
 * @author autogenerated
 */
public interface InvoicePaymentsDao extends GenericDAO<InvoicePayments,  Integer>  {
	// constructor only
}

