package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasInvoices;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasInvoicesPK;
/**
 * DAO interface for table: ProjectsHasInvoices.
 * @author autogenerated
 */
public interface ProjectsHasInvoicesDao extends GenericDAO<ProjectsHasInvoices,  ProjectsHasInvoicesPK>  {
	// constructor only
}

