package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasConnectionsPK;
import java.io.Serializable;
/**
 * DAO interface for table: ProjectsHasConnectionsPK.
 * @author autogenerated
 */
public interface ProjectsHasConnectionsPKDao extends GenericDAO<ProjectsHasConnectionsPK,  Serializable>  {
	// constructor only
}

