package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasInvoicesPK;
import java.io.Serializable;
/**
 * DAO interface for table: ProjectsHasInvoicesPK.
 * @author autogenerated
 */
public interface ProjectsHasInvoicesPKDao extends GenericDAO<ProjectsHasInvoicesPK,  Serializable>  {
	// constructor only
}

