package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasQuotesPK;
import java.io.Serializable;
/**
 * DAO interface for table: ProjectsHasQuotesPK.
 * @author autogenerated
 */
public interface ProjectsHasQuotesPKDao extends GenericDAO<ProjectsHasQuotesPK,  Serializable>  {
	// constructor only
}

