package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasConnections;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasConnectionsPK;
/**
 * DAO interface for table: ProjectsHasConnections.
 * @author autogenerated
 */
public interface ProjectsHasConnectionsDao extends GenericDAO<ProjectsHasConnections,  ProjectsHasConnectionsPK>  {
	// constructor only
}

