package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasQuotes;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasQuotesPK;
/**
 * DAO interface for table: ProjectsHasQuotes.
 * @author autogenerated
 */
public interface ProjectsHasQuotesDao extends GenericDAO<ProjectsHasQuotes,  ProjectsHasQuotesPK>  {
	// constructor only
}

