package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.Projects;
 
/**
 * DAO interface for table: Projects.
 * @author autogenerated
 */
public interface ProjectsDao extends GenericDAO<Projects,  Integer>  {
	// constructor only
}

