package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.QuoteItems;
 
/**
 * DAO interface for table: QuoteItems.
 * @author autogenerated
 */
public interface QuoteItemsDao extends GenericDAO<QuoteItems,  Integer>  {
	// constructor only
}

