package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.Quotes;
 
/**
 * DAO interface for table: Quotes.
 * @author autogenerated
 */
public interface QuotesDao extends GenericDAO<Quotes,  Integer>  {
	// constructor only
}

