package com.datavirtue.nevitiumpro.data.model.dao;

import com.felees.hbnpojogen.persistence.GenericDAO;
import com.datavirtue.nevitiumpro.data.model.obj.UserAccounts;
 
/**
 * DAO interface for table: UserAccounts.
 * @author autogenerated
 */
public interface UserAccountDao extends GenericDAO<UserAccounts,  Integer>  {
	// constructor only
}

