package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.ConnectionsDocuments;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.ConnectionsDocumentsDao;
 
 
/**
 * DAO for table: ConnectionsDocuments.
 * @author autogenerated
 */
@Repository
public class ConnectionsDocumentsDaoImpl extends GenericHibernateDaoImpl<ConnectionsDocuments, Integer> implements ConnectionsDocumentsDao {
	
	/** Constructor method. */
		public ConnectionsDocumentsDaoImpl() {
			super(ConnectionsDocuments.class);
		}
	}

