package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.Connections;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.ConnectionsDao;
 
 
/**
 * DAO for table: Connections.
 * @author autogenerated
 */
@Repository
public class ConnectionsDaoImpl extends GenericHibernateDaoImpl<Connections, Integer> implements ConnectionsDao {
	
	/** Constructor method. */
		public ConnectionsDaoImpl() {
			super(Connections.class);
		}
	}

