package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.ConnectionsShipping;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.ConnectionsShippingDao;
 
 
/**
 * DAO for table: ConnectionsShipping.
 * @author autogenerated
 */
@Repository
public class ConnectionsShippingDaoImpl extends GenericHibernateDaoImpl<ConnectionsShipping, Integer> implements ConnectionsShippingDao {
	
	/** Constructor method. */
		public ConnectionsShippingDaoImpl() {
			super(ConnectionsShipping.class);
		}
	}

