package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.CreditAccountLedger;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.CreditAccountLedgerDao;
 
 
/**
 * DAO for table: CreditAccountLedger.
 * @author autogenerated
 */
@Repository
public class CreditAccountLedgerDaoImpl extends GenericHibernateDaoImpl<CreditAccountLedger, Integer> implements CreditAccountLedgerDao {
	
	/** Constructor method. */
		public CreditAccountLedgerDaoImpl() {
			super(CreditAccountLedger.class);
		}
	}

