package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.CreditAccounts;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.CreditAccountsDao;
 
 
/**
 * DAO for table: CreditAccounts.
 * @author autogenerated
 */
@Repository
public class CreditAccountsDaoImpl extends GenericHibernateDaoImpl<CreditAccounts, Integer> implements CreditAccountsDao {
	
	/** Constructor method. */
		public CreditAccountsDaoImpl() {
			super(CreditAccounts.class);
		}
	}

