package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.DebitAccountLedger;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.DebitAccountLedgerDao;
 
 
/**
 * DAO for table: DebitAccountLedger.
 * @author autogenerated
 */
@Repository
public class DebitAccountLedgerDaoImpl extends GenericHibernateDaoImpl<DebitAccountLedger, Integer> implements DebitAccountLedgerDao {
	
	/** Constructor method. */
		public DebitAccountLedgerDaoImpl() {
			super(DebitAccountLedger.class);
		}
	}

