package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.DebitAccounts;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.DebitAccountsDao;
 
 
/**
 * DAO for table: DebitAccounts.
 * @author autogenerated
 */
@Repository
public class DebitAccountsDaoImpl extends GenericHibernateDaoImpl<DebitAccounts, Integer> implements DebitAccountsDao {
	
	/** Constructor method. */
		public DebitAccountsDaoImpl() {
			super(DebitAccounts.class);
		}
	}

