package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.InventoryImages;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.InventoryImagesDao;
 
 
/**
 * DAO for table: InventoryImages.
 * @author autogenerated
 */
@Repository
public class InventoryImagesDaoImpl extends GenericHibernateDaoImpl<InventoryImages, Integer> implements InventoryImagesDao {
	
	/** Constructor method. */
		public InventoryImagesDaoImpl() {
			super(InventoryImages.class);
		}
	}

