package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.Inventory;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.InventoryDao;
 
 
/**
 * DAO for table: Inventory.
 * @author autogenerated
 */
@Repository
public class InventoryDaoImpl extends GenericHibernateDaoImpl<Inventory, Integer> implements InventoryDao {
	
	/** Constructor method. */
		public InventoryDaoImpl() {
			super(Inventory.class);
		}
	}

