package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.InvoicePayments;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.InvoicePaymentsDao;
 
 
/**
 * DAO for table: InvoicePayments.
 * @author autogenerated
 */
@Repository
public class InvoicePaymentsDaoImpl extends GenericHibernateDaoImpl<InvoicePayments, Integer> implements InvoicePaymentsDao {
	
	/** Constructor method. */
		public InvoicePaymentsDaoImpl() {
			super(InvoicePayments.class);
		}
	}

