package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.InvoiceItems;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.InvoiceItemsDao;
 
 
/**
 * DAO for table: InvoiceItems.
 * @author autogenerated
 */
@Repository
public class InvoiceItemsDaoImpl extends GenericHibernateDaoImpl<InvoiceItems, Integer> implements InvoiceItemsDao {
	
	/** Constructor method. */
		public InvoiceItemsDaoImpl() {
			super(InvoiceItems.class);
		}
	}

