package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.Invoices;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.InvoicesDao;
 
 
/**
 * DAO for table: Invoices.
 * @author autogenerated
 */
@Repository
public class InvoicesDaoImpl extends GenericHibernateDaoImpl<Invoices, Integer> implements InvoicesDao {
	
	/** Constructor method. */
		public InvoicesDaoImpl() {
			super(Invoices.class);
		}
	}

