package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.InvoiceReturns;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.InvoiceReturnsDao;
 
 
/**
 * DAO for table: InvoiceReturns.
 * @author autogenerated
 */
@Repository
public class InvoiceReturnsDaoImpl extends GenericHibernateDaoImpl<InvoiceReturns, Integer> implements InvoiceReturnsDao {
	
	/** Constructor method. */
		public InvoiceReturnsDaoImpl() {
			super(InvoiceReturns.class);
		}
	}

