package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasQuotesPK;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.ProjectsHasQuotesPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: ProjectsHasQuotesPK.
 * @author autogenerated
 */
@Repository
public class ProjectsHasQuotesPKDaoImpl extends GenericHibernateDaoImpl<ProjectsHasQuotesPK, Serializable> implements ProjectsHasQuotesPKDao {
	
	/** Constructor method. */
		public ProjectsHasQuotesPKDaoImpl() {
			super(ProjectsHasQuotesPK.class);
		}
	}

