package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasQuotes;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.ProjectsHasQuotesDao;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasQuotesPK;
 
/**
 * DAO for table: ProjectsHasQuotes.
 * @author autogenerated
 */
@Repository
public class ProjectsHasQuotesDaoImpl extends GenericHibernateDaoImpl<ProjectsHasQuotes, ProjectsHasQuotesPK> implements ProjectsHasQuotesDao {
	
	/** Constructor method. */
		public ProjectsHasQuotesDaoImpl() {
			super(ProjectsHasQuotes.class);
		}
	}

