package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasInvoices;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.ProjectsHasInvoicesDao;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasInvoicesPK;
 
/**
 * DAO for table: ProjectsHasInvoices.
 * @author autogenerated
 */
@Repository
public class ProjectsHasInvoicesDaoImpl extends GenericHibernateDaoImpl<ProjectsHasInvoices, ProjectsHasInvoicesPK> implements ProjectsHasInvoicesDao {
	
	/** Constructor method. */
		public ProjectsHasInvoicesDaoImpl() {
			super(ProjectsHasInvoices.class);
		}
	}

