package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.ProjectsHasInvoicesPK;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.ProjectsHasInvoicesPKDao;
import java.io.Serializable;
 
/**
 * DAO for table: ProjectsHasInvoicesPK.
 * @author autogenerated
 */
@Repository
public class ProjectsHasInvoicesPKDaoImpl extends GenericHibernateDaoImpl<ProjectsHasInvoicesPK, Serializable> implements ProjectsHasInvoicesPKDao {
	
	/** Constructor method. */
		public ProjectsHasInvoicesPKDaoImpl() {
			super(ProjectsHasInvoicesPK.class);
		}
	}

