package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.QuoteItems;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.QuoteItemsDao;
 
 
/**
 * DAO for table: QuoteItems.
 * @author autogenerated
 */
@Repository
public class QuoteItemsDaoImpl extends GenericHibernateDaoImpl<QuoteItems, Integer> implements QuoteItemsDao {
	
	/** Constructor method. */
		public QuoteItemsDaoImpl() {
			super(QuoteItems.class);
		}
	}

