package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.Quotes;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.QuotesDao;
 
 
/**
 * DAO for table: Quotes.
 * @author autogenerated
 */
@Repository
public class QuotesDaoImpl extends GenericHibernateDaoImpl<Quotes, Integer> implements QuotesDao {
	
	/** Constructor method. */
		public QuotesDaoImpl() {
			super(Quotes.class);
		}
	}

