package com.datavirtue.nevitiumpro.data.model.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import com.datavirtue.nevitiumpro.data.model.obj.UserAccounts;
import org.springframework.stereotype.Repository;
import com.datavirtue.nevitiumpro.data.model.dao.UserAccountDao;
 
 
/**
 * DAO for table: UserAccounts.
 * @author autogenerated
 */
@Repository
public class UserAccountDaoImpl extends GenericHibernateDaoImpl<UserAccounts, Integer> implements UserAccountDao {
	
	/** Constructor method. */
		public UserAccountDaoImpl() {
			super(UserAccounts.class);
		}
	}

